use std::fmt;

#[derive(PartialEq, Eq, PartialOrd, Ord, Debug, Clone, Copy, Hash)]
pub enum Keyword {
    And,
    As,
    Asc,
    Alter,
    Add,
    Begin,
    Bool,
    Boolean,
    By,
    Char,
    Commit,
    Create,
    Cross,
    Column,
    Committed,
    Default,
    Delete,
    Desc,
    Double,
    Drop,
    Databases,
    Describe,
    Explain,
    False,
    Float,
    From,
    Group,
    Global,
    Having,
    Level,
    Index,
    Infinity,
    Inner,
    Insert,
    Int,
    Integer,
    Into,
    Is,
    Isolation,
    Join,
    Key,
    Left,
    Like,
    Limit,
    Modify,
    NaN,
    Not,
    Null,
    Of,
    Offset,
    On,
    Only,
    Or,
    Order,
    Outer,
    Primary,
    Read,
    References,
    Right,
    Rollback,
    Rename,
    Repeatable,
    Select,
    Set,
    String,
    System,
    Session,
    Show,
    Serializable,
    To,
    Table,
    Tables,
    Text,
    Time,
    Transaction,
    True,
    Unique,
    Uncommitted,
    Update,
    Values,
    VarChar,
    Where,
    Write,
    UserIdent,
    Int8,
    Int16,
    Int32,
    Int64,
    Uint8,
    Uint16,
    Uint32,
    Uint64,
    Float32,
    Float64,
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "keyword: {}",
            match self {
                Self::And => "And",
                Self::As => "As",
                Self::Asc => "Asc",
                Self::Add => "Add",
                Self::Alter => "Alter",
                Self::Begin => "Begin",
                Self::Bool => "Bool",
                Self::Boolean => "Boolean",
                Self::By => "By",
                Self::Char => "Char",
                Self::Commit => "Commit",
                Self::Create => "Create",
                Self::Cross => "Cross",
                Self::Column => "Column",
                Self::Committed => "Commited",
                Self::Default => "Default",
                Self::Delete => "Delete",
                Self::Desc => "Desc",
                Self::Double => "Double",
                Self::Drop => "Drop",
                Self::Databases => "Databases",
                Self::Describe => "Describe",
                Self::Explain => "Explain",
                Self::False => "False",
                Self::Float => "Float",
                Self::From => "From",
                Self::Group => "Group",
                Self::Global => "Global",
                Self::Having => "Having",
                Self::Level => "Level",
                Self::Index => "Index",
                Self::Infinity => "Infinity",
                Self::Inner => "Inner",
                Self::Insert => "Insert",
                Self::Int => "Int",
                Self::Integer => "Integer",
                Self::Into => "Into",
                Self::Is => "Is",
                Self::Isolation => "Isolation",
                Self::Join => "Join",
                Self::Key => "Key",
                Self::Left => "Left",
                Self::Like => "Like",
                Self::Limit => "Limit",
                Self::Modify => "Modify",
                Self::NaN => "Nan",
                Self::Not => "Not",
                Self::Null => "Null",
                Self::Of => "Of",
                Self::Offset => "Offset",
                Self::On => "On",
                Self::Only => "Only",
                Self::Or => "Or",
                Self::Order => "Order",
                Self::Outer => "Outer",
                Self::Primary => "Primary",
                Self::Read => "Read",
                Self::References => "References",
                Self::Right => "Right",
                Self::Rollback => "Rollback",
                Self::Rename => "Rename",
                Self::Select => "Select",
                Self::Set => "Set",
                Self::String => "String",
                Self::Show => "Show",
                Self::System => "System",
                Self::Session => "Session",
                Self::Serializable => "Serializable",
                Self::Table => "Table",
                Self::Tables => "Tables",
                Self::Text => "Text",
                Self::Time => "Time",
                Self::Transaction => "Transaction",
                Self::True => "True",
                Self::To => "To",
                Self::Unique => "Unique",
                Self::Update => "Update",
                Self::Values => "Values",
                Self::VarChar => "Varchar",
                Self::Where => "Where",
                Self::Write => "Write",
                Self::Repeatable => "Repeatable",
                Self::Uncommitted => "Uncommited",
                Self::UserIdent => "UserIdent",
                Self::Int8 => "Int8",
                Self::Int16 => "Int16",
                Self::Int32 => "Int32",
                Self::Int64 => "Int64",
                Self::Uint8 => "Uint8",
                Self::Uint16 => "Uint16",
                Self::Uint32 => "Uint32",
                Self::Uint64 => "Uint64",
                Self::Float32 => "Float32",
                Self::Float64 => "Float64",
            }
        )
    }
}

pub fn find_keyword(keyword_str: &str) -> Keyword {
    // 转化为大写
    let upper_keyword_str = keyword_str.to_uppercase();

    match upper_keyword_str.as_str() {
        "AND" => Keyword::And,
        "AS" => Keyword::As,
        "ASC" => Keyword::Asc,
        "ADD" => Keyword::Add,
        "ALTER" => Keyword::Alter,
        "BEGIN" => Keyword::Begin,
        "BOOL" => Keyword::Bool,
        "BOOLEAN" => Keyword::Boolean,
        "BY" => Keyword::By,
        "CHAR" => Keyword::Char,
        "COMMIT" => Keyword::Commit,
        "CREATE" => Keyword::Create,
        "CROSS" => Keyword::Cross,
        "COLUMN" => Keyword::Column,
        "DEFAULT" => Keyword::Default,
        "DELETE" => Keyword::Delete,
        "DESC" => Keyword::Desc,
        "DOUBLE" => Keyword::Double,
        "DROP" => Keyword::Drop,
        "DATABASES" => Keyword::Databases,
        "DESCRIBE" => Keyword::Describe,
        "EXPLAIN" => Keyword::Explain,
        "FALSE" => Keyword::False,
        "FLOAT" => Keyword::Float,
        "FROM" => Keyword::From,
        "GROUP" => Keyword::Group,
        "GLOBAL" => Keyword::Global,
        "HAVING" => Keyword::Having,
        "INDEX" => Keyword::Index,
        "INFINITY" => Keyword::Infinity,
        "INNER" => Keyword::Inner,
        "INTEGER" => Keyword::Integer,
        "INSERT" => Keyword::Insert,
        "INT" => Keyword::Int,
        "INTO" => Keyword::Into,
        "IS" => Keyword::Is,
        "LEVEL" => Keyword::Level,
        "TRANSACTION" => Keyword::Transaction,
        "ISOLATION" => Keyword::Isolation,
        "READ" => Keyword::Read,
        "COMMITTED" => Keyword::Committed,
        "JOIN" => Keyword::Join,
        "KEY" => Keyword::Key,
        "LEFT" => Keyword::Left,
        "LIKE" => Keyword::Like,
        "LIMIT" => Keyword::Limit,
        "NAN" => Keyword::NaN,
        "NOT" => Keyword::Not,
        "NULL" => Keyword::Null,
        "OF" => Keyword::Of,
        "OFFSET" => Keyword::Offset,
        "ON" => Keyword::On,
        "ONLY" => Keyword::Only,
        "OR" => Keyword::Or,
        "ORDER" => Keyword::Order,
        "OUTER" => Keyword::Outer,
        "PRIMARY" => Keyword::Primary,
        "REFERENCES" => Keyword::References,
        "RIGHT" => Keyword::Right,
        "ROLLBACK" => Keyword::Rollback,
        "RENAME" => Keyword::Rename,
        "SELECT" => Keyword::Select,
        "STRING" => Keyword::String,
        "SHOW" => Keyword::Show,
        "SET" => Keyword::Set,
        "SYSTEM" => Keyword::System,
        "SESSION" => Keyword::Session,
        "TABLE" => Keyword::Table,
        "TABLES" => Keyword::Tables,
        "TEXT" => Keyword::Text,
        "TIME" => Keyword::Time,
        "TRUE" => Keyword::True,
        "TO" => Keyword::To,
        "UNIQUE" => Keyword::Unique,
        "UPDATE" => Keyword::Update,
        "VALUES" => Keyword::Values,
        "VARCHAR" => Keyword::VarChar,
        "WHERE" => Keyword::Where,
        "WRITE" => Keyword::Write,
        "MODIFY" => Keyword::Modify,
        "REPEATABLE" => Keyword::Repeatable,
        "UNCOMMITTED" => Keyword::Uncommitted,
        "SERIALIZABLE" => Keyword::Serializable,
        "INT8" => Keyword::Int8,
        "INT16" => Keyword::Int16,
        "INT32" => Keyword::Int32,
        "INT64" => Keyword::Int64,
        "UINT8" => Keyword::Uint8,
        "UINT16" => Keyword::Uint16,
        "UINT32" => Keyword::Uint32,
        "UINT64" => Keyword::Uint64,
        "FLOAT32" => Keyword::Float32,
        "FLOAT64" => Keyword::Float64,
        _ => Keyword::UserIdent,
    }
}
